/**
 * Defines movement routes for each player color.
 * Each route is an ordered list of board coordinates (row, col)
 * representing the path a piece follows.
 */
export const routes = {
  red: [
    { row: 4, col: 6, final: 0 },
    { row: 5, col: 6, final: 0 },
    { row: 6, col: 5, final: 0 },
    { row: 6, col: 4, final: 0 },
    { row: 6, col: 3, final: 0 },
    { row: 6, col: 2, final: 0 },
    { row: 6, col: 1, final: 0 },
    { row: 6, col: 0, final: 0 },
    { row: 7, col: 0, final: 0 },
    { row: 8, col: 0, final: 0 },
    { row: 8, col: 1, final: 0 },
    { row: 8, col: 2, final: 0 },
    { row: 8, col: 3, final: 0 },
    { row: 8, col: 4, final: 0 },
    { row: 8, col: 5, final: 0 },
    { row: 9, col: 6, final: 0 },
    { row: 10, col: 6, final: 0 },
    { row: 11, col: 6, final: 0 },
    { row: 12, col: 6, final: 0 },
    { row: 13, col: 6, final: 0 },
    { row: 14, col: 6, final: 0 },
    { row: 14, col: 7, final: 0 },
    { row: 14, col: 8, final: 0 },
    { row: 13, col: 8, final: 0 },
    { row: 12, col: 8, final: 0 },
    { row: 11, col: 8, final: 0 },
    { row: 10, col: 8, final: 0 },
    { row: 9, col: 8, final: 0 },
    { row: 8, col: 9, final: 0 },
    { row: 8, col: 10, final: 0 },
    { row: 8, col: 11, final: 0 },
    { row: 8, col: 12, final: 0 },
    { row: 8, col: 13, final: 0 },
    { row: 8, col: 14, final: 0 },
    { row: 7, col: 14, final: 0 },
    { row: 6, col: 14, final: 0 },
    { row: 6, col: 13, final: 0 },
    { row: 6, col: 12, final: 0 },
    { row: 6, col: 11, final: 0 },
    { row: 6, col: 10, final: 0 },
    { row: 6, col: 9, final: 0 },
    { row: 5, col: 8, final: 0 },
    { row: 4, col: 8, final: 0 },
    { row: 3, col: 8, final: 0 },
    { row: 2, col: 8, final: 0 },
    { row: 1, col: 8, final: 0 },
    { row: 0, col: 8, final: 0 },
    { row: 0, col: 7, final: 0 },
    { row: 0, col: 6, final: 0 },
    { row: 1, col: 6, final: 0 },
    { row: 2, col: 6, final: 0 },
    { row: 3, col: 6, final: 0 },
    { row: 4, col: 6, final: 0 },
    { row: 5, col: 6, final: 0 },
    { row: 6, col: 5, final: 0 },
    { row: 6, col: 4, final: 0 },
    { row: 6, col: 3, final: 0 },
    { row: 6, col: 2, final: 0 },
    { row: 6, col: 1, final: 0 },
    { row: 6, col: 0, final: 0 },
    { row: 7, col: 0, final: 1 },
    { row: 7, col: 1, final: 1 },
    { row: 7, col: 2, final: 1 },
    { row: 7, col: 3, final: 1 },
    { row: 7, col: 4, final: 1 },
    { row: 7, col: 5, final: 1 },
    { row: 7, col: 6, final: 1 },
  ],
};
